[bootstrap.packages]
"brew:starship" = "latest"
"brew:zoxide" = "latest"
"brew:eza" = "latest"
"brew:direnv" = "latest"
"brew:ripgrep" = "latest"
"brew:ugrep" = "latest"
"brew:fd" = "latest"
"brew:bat" = "latest"
"brew:yq" = "latest"
"brew:btop" = "latest"
"brew:kubectl" = "latest"
"brew:neovim" = "latest"
"brew:tini" = "latest"
"brew:gh" = "latest"
"brew:mise" = "latest"
"brew:librsvg" = "latest"
"brew:ddev/ddev/ddev" = "latest"
"brew:hashicorp/tap/terraform" = "latest"
