[tools]
aws-cli = "latest"
aws-sam = "latest"
btop = "latest"
cargo-binstall = "latest"
"cargo:mdbook" = "latest"
cosign = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
"github:ddev/ddev" = "latest"
"github:terrastruct/d2" = "latest"
go = "latest"
helm = "latest"
"http:ugrep" = { version = "7.5.0", url = "https://nightly.link/Genivia/ugrep/workflows/autobuild-static/v7.5.0/ugrep_amd64_eada755_2506181906.zip" }
hurl = "latest"
jq = "latest"
just = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
kustomize = "latest"
lazygit = "latest"
lychee = "latest"
node = "latest"
"npm:@devcontainers/cli" = "latest"
"pipx:azure-cli" = { version = "latest", uvx_args = "--prerelease=allow" }
"pipx:httpie" = "latest"
"pipx:rumdl" = "latest"
pnpm = "latest"
python = "latest"
restic = "latest"
rg = "latest"
rustic = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
vault = "latest"
yq = "latest"
zellij = "latest"

[settings]
experimental = true
pipx.uvx = true
