[tools]
# Language Runtimes & Development
## Languages
go = "latest"
node = "latest" 
python = "latest"

## Package Managers
pnpm = "latest"
uv = "latest"
pipx = "latest"

## Build Tools
just = "latest"
yq = "latest"

# Cloud & Kubernetes
## AWS
aws-cli = "latest"
aws-sam = "latest"

## Kubernetes
kubectl = "latest"
k9s = "latest"
k3d = "latest"
kustomize = "latest"

## Infrastructure
tflint = "latest"
terraform-docs = "latest"

## Security
trivy = "latest"
vault = "latest"

# Productivity & Terminal
## Terminal
zellij = "latest"
starship = "latest"
zoxide = "latest"
eza = "latest"
direnv = "latest"
"pipx:tldr" = "latest"

## Git
lazygit = "latest"

## Documentation
"cargo:mdbook" = "latest"
lychee = "latest"
"ubi:rvben/rumdl" = "latest"

## Testing
hurl = "latest"
"pipx:httpie" = "latest"
semgrep = "latest"

## Package Managers
"npm:@devcontainers/cli" = "latest"
cargo-binstall = "latest"

## Code Analysis
"ubi:boyter/scc" = "latest"

## Local Development
localstack = "latest"

[settings]
python.compile = false
pipx.uvx = true
trusted_config_paths = ["/workspaces"]
