[tools]
# Cloud CLIs (AWS only - others installed via Debian packages)
aws-cli = "latest"
aws-sam = "latest"

# Container orchestration  
helm = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
kustomize = "latest"

# Languages & runtimes
go = "latest"
node = "latest"
python = "latest"
pnpm = "latest"

# Infrastructure & security
terraform = "latest"
trivy = "latest"
cosign = "latest"
vault = "latest"

# Development tools
just = "latest"
yq = "latest"
hurl = "latest"
lychee = "latest"

# Documentation & diagrams
"cargo:mdbook" = "latest"
"github:terrastruct/d2" = "latest"

# Backup & recovery
restic = "latest"
rustic = "latest"

# Terminal & productivity  
zellij = "latest"
lazygit = "latest"

# Package managers
cargo-binstall = "latest"
"npm:@devcontainers/cli" = "latest"
"pipx:httpie" = "latest"
"pipx:rumdl" = "latest"
starship = "latest"

[settings]
experimental = true
pipx.uvx = true
