[tools]
aws-cli = "latest"
aws-sam = "latest"
cargo-binstall = "latest"
"cargo:mdbook" = "latest"
cosign = "latest"
gcloud = "latest"
"github:ddev/ddev" = "latest"
"github:terrastruct/d2" = "latest"
go = "latest"
helm = "latest"
hurl = "latest"
jq = "latest"
just = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
kustomize = "latest"
lychee = "latest"
node = "latest"
"pipx:azure-cli" = "latest"
"pipx:rumdl" = "latest"
pnpm = "latest"
python = "latest"
restic = "latest"
rg = "latest"
rustic = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"

[settings]
experimental = true